name: JDailyBonus-Actions

on:
  push:
    branches: 
      - master
    paths:
      - '.github/workflows/**'
  schedule:
    - cron: '0 0 * * *'
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
    - name: Clone Repository
      uses: actions/checkout@v1

    - name: Setup Node.js 12.x
      uses: actions/setup-node@v2
      with:
        node-version: '12'
        
    - name: JD Bonus
      env:
        MyJDCookie01: ${{ secrets.JDCOOKIE01 }}
        MyJDCookie02: ${{ secrets.JDCOOKIE02 }}
      run: |
        MyJDCookie01=$(echo ${MyJDCookie01} | sed 's/\//\\\//')
        MyJDCookie02=$(echo ${MyJDCookie02} | sed 's/\//\\\//')
        wget https://raw.githubusercontent.com/NobyDa/Script/master/JD-DailyBonus/JD_DailyBonus.js
        sed -i "s/var Key = '';/var Key = '${MyJDCookie01}';/" JD_DailyBonus.js
        sed -i "s/var DualKey = '';/var DualKey = '${MyJDCookie02}';/" JD_DailyBonus.js
        sudo -E npm install request
        node JD_DailyBonus.js

